name = "Svelte"
grammar = "svelte"
path_suffixes = ["svelte"]
block_comment = ["<!-- ", " -->"]

# Not sure what these are for, so will await feedback
# autoclose_before = ";:.,=}])>"
prettier_parser_name = "svelte"
prettier_plugins = ["prettier-plugin-svelte"]
